# Generated by Django 4.2.1 on 2023-05-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drishti', '0003_alter_catscreen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catscreen',
            name='score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catscreen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drishti.drishtiuser'),
        ),
    ]
